# Base configs
url: "https://tuechile.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Tue Chi"
subtitle: "mosaics"
author:  "Tue Chi Le"
header:
 title: "Photography"
 subtitle: "by Tue Chi Le"
footer:
 name: "Hello World! 👋'"
 bio: "Hi I am Chi"
social_urls:
  instagram: "https://www.instagram.com/pju_irza/"