# Base configs
url: "https://tuechile.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Pirenily"
subtitle: "mosaics"
author:  "Le Tue Chi"
header:
 title: "Pirenily"
 subtitle: "by Tue-Chi Le"
footer:
 name: "My name is Chi, or Tuệ Chi."
 bio: "I use Pirenily as a vessel of self-expression: through graphic design, photography, and storyboards."
 bio2: "My main interests lie in the construction of interdependence: of time depiction through visual effects, of the existence of the multiverse through doors-and-paths related design, of myself as a locus of socialization."
 bio3: "Every form of visual presentation on this website is mainly experimented, taken, edited, scripted, and modeled by me."
 reminder: "The blog (and albums, check them out!) is best experienced when viewed with one or three images per row."
social_urls:
  instagram: "https://www.instagram.com/pju_irza/"