# Base configs
url: "https://tuechile.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Pirenily"
subtitle: "mosaics"
author:  "Le Tue Chi"
header:
 title: "Pirenily"
 subtitle: "by Tue-Chi Le"
footer:
 name: "My name is Lê Tuệ Chi or Chi Le, and I am a self-taught illustrator and graphic designer based in Cambridge, MA."
 bio: "My passion for film and installation art grows within my identity: pirenily. I use Pirenily as a vessel of self-expression: through graphic design, photography, and storyboards. My main interests lie in the construction of interdependence: of time depiction through visual effects, of the existence of the multiverse through doors-and-paths-related design, and of myself as a locus of socialization. Every form of visual presentation on this website is mainly experimented, taken, edited, scripted, and modeled by me."
 bio2: "I spent my K-12 education in Hanoi, Vietnam which ended in my graduation from Foreign Language Specialized School. Most of my collaborative work in high school was devoted to the International Vietnam Model UN, Recit Studio, and CNN English Club. I am currently a freshman at Harvard College with undecided major declaration, but I am mainly looking into a concentration in Electrical and Computer Engineering and a secondary in Art, Film, and Visual Studies. I am a part of Harvard Undergraduate Design Collective and Harvard Undergraduate in Asia Program."
 reminder: "The blog (including the albums, check them out!) is best experienced when viewed with one or three images per row."
social_urls:
  instagram: "https://www.instagram.com/pju_irza/"