# Base configs
url: "https://tuechile.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Pirenily"
subtitle: "mosaics"
author:  "Tue Chi Le"
header:
 title: "Pirenily"
 subtitle: "by Tue Chi Le"
footer:
 name: "My name is Chi, or Tuệ Chi."
 bio: "Sometimes I use Pirenily as a vessel of self-expression: through graphic design, photography, and storyboards. Other times I am Chi, a student from Vietnam."
 reminder: "The blog is best experienced when viewed with three images per row."
social_urls:
  instagram: "https://www.instagram.com/pju_irza/"